#!/bin/bash

VKRUNNER_PATH=external/vkrunner
INITIAL_SCRIPT_DIR=$VKRUNNER_PATH/examples
INITIAL_SCRIPTS=`ls $INITIAL_SCRIPT_DIR`

PRECOMPILE_PROGRAM=$VKRUNNER_PATH/precompile-script.py

OUTPUT_DIR=app
OUTPUT=$OUTPUT_DIR/string_scripts.inc

echo "// Generated by $0 based on scripts in $INITIAL_SCRIPT_DIR." > $OUTPUT

function process() {
  script_dir=$1
  script=$2

  echo
  echo
  echo Processing $OUTPUT_DIR/$script

  tmp=$OUTPUT_DIR/$script.tmp
  $PRECOMPILE_PROGRAM $script_dir/$script -o $tmp
  echo R\"\( > $OUTPUT_DIR/$script
  cat $tmp >> $OUTPUT_DIR/$script
  echo \)\", >> $OUTPUT_DIR/$script
  rm $tmp

  echo \#include \"$script\" >> $OUTPUT
}

if [[ ! -z $1 ]]; then
  target=$1
  target_dir="$(dirname "$target")"
  target=${target##*/}
  process $target_dir $target
else
  for target in $INITIAL_SCRIPTS
  do
    process $INITIAL_SCRIPT_DIR $target
  done
fi

echo
echo
echo See \"$OUTPUT\" and files in \"$OUTPUT_DIR\"
